const {compile} = require('json-schema-to-typescript');
const {writeFile, readdir, stat} = require('node:fs/promises');

const FILE_PREFIX = `/* eslint-disable */
/**
 * This file was automatically generated by validationCompile.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run jsonSchema2ts.js to regenerate this file.
 */
`;

const VALIDATION_SRC = './validations';
const VALIDATION_DST = './src/validations';

async function handleSchema(data) {
    return (
        await Promise.all(
            Object.keys(data).map(async (ns) => {
                const header = `export namespace ${ns} {\n`;
                const content =
                    ' '.repeat(2) +
                    (
                        await Promise.all(
                            Object.keys(data[ns]).map(async (method) => {
                                const types = await compile({
                                    ...data[ns][method],
                                    title: method
                                });
                                return `export${types.split('export').pop()}`;
                            })
                        )
                    )
                        .join('')
                        .replaceAll('\n', '\n  ')
                        .slice(0, -2);
                const footer = '}\n';
                return [header, content, footer].join('');
            })
        )
    ).join('');
}

(async () => {
    const dir = await readdir(VALIDATION_SRC);
    for (const entry of dir) {
        const path = `${VALIDATION_SRC}/${entry}`;
        let schema;
        let outputFileName;
        if ((await stat(path)).isDirectory()) {
            schema = {};
            outputFileName = `${entry}.d.ts`;
            for (const pathEntry of await readdir(path)) {
                const name = pathEntry.split('.', 1)[0];
                schema[name] = require(`${path}/${pathEntry}`);
            }
        } else {
            schema = require(path);
            outputFileName = entry.replace('.json', '.d.ts');
        }
        const res = await handleSchema(schema);
        await writeFile(
            `${VALIDATION_DST}/${outputFileName}`,
            FILE_PREFIX + res,
            {
                flag: 'w'
            }
        );
    }
})();
