export const bthomeObjectInfos: Record<
    number,
    {
        name: string;
        type: 'sensor' | 'binary_sensor' | 'dimmer' | 'button';
        unit: string;
    }
> = {
    1: {name: 'battery', type: 'sensor', unit: '%'},
    2: {name: 'temperature', type: 'sensor', unit: '°C'},
    3: {name: 'humidity', type: 'sensor', unit: '%'},
    4: {name: 'pressure', type: 'sensor', unit: 'hPa'},
    5: {name: 'illuminance', type: 'sensor', unit: 'lux'},
    6: {name: 'mass_kg', type: 'sensor', unit: 'kg'},
    7: {name: 'mass_lb', type: 'sensor', unit: 'lb'},
    8: {name: 'dewpoint', type: 'sensor', unit: '°C'},
    9: {name: 'count', type: 'sensor', unit: ''},
    10: {name: 'energy', type: 'sensor', unit: 'kWh'},
    11: {name: 'power', type: 'sensor', unit: 'W'},
    12: {name: 'voltage', type: 'sensor', unit: 'V'},
    13: {name: 'pm2.5', type: 'sensor', unit: 'ug/m3'},
    14: {name: 'pm10', type: 'sensor', unit: 'ug/m3'},
    15: {name: 'generic_boolean', type: 'binary_sensor', unit: ''},
    16: {name: 'power_status', type: 'binary_sensor', unit: ''},
    17: {name: 'opening', type: 'binary_sensor', unit: ''},
    18: {name: 'co2', type: 'sensor', unit: 'ppm'},
    19: {name: 'tvoc', type: 'sensor', unit: 'ug/m3'},
    20: {name: 'moisture', type: 'sensor', unit: '%'},
    21: {name: 'battery_status', type: 'binary_sensor', unit: ''},
    22: {name: 'battery_charging', type: 'binary_sensor', unit: ''},
    23: {name: 'carbon_monoxide', type: 'binary_sensor', unit: ''},
    24: {name: 'cold', type: 'binary_sensor', unit: ''},
    25: {name: 'connectivity', type: 'binary_sensor', unit: ''},
    26: {name: 'door', type: 'binary_sensor', unit: ''},
    27: {name: 'garage_door', type: 'binary_sensor', unit: ''},
    28: {name: 'gas', type: 'binary_sensor', unit: ''},
    29: {name: 'heat', type: 'binary_sensor', unit: ''},
    30: {name: 'light', type: 'binary_sensor', unit: ''},
    31: {name: 'lock', type: 'binary_sensor', unit: ''},
    32: {name: 'moisture', type: 'binary_sensor', unit: ''},
    33: {name: 'motion', type: 'binary_sensor', unit: ''},
    34: {name: 'moving', type: 'binary_sensor', unit: ''},
    35: {name: 'occupancy', type: 'binary_sensor', unit: ''},
    36: {name: 'plug', type: 'binary_sensor', unit: ''},
    37: {name: 'presence', type: 'binary_sensor', unit: ''},
    38: {name: 'problem', type: 'binary_sensor', unit: ''},
    39: {name: 'running', type: 'binary_sensor', unit: ''},
    40: {name: 'safety', type: 'binary_sensor', unit: ''},
    41: {name: 'smoke', type: 'binary_sensor', unit: ''},
    42: {name: 'sound', type: 'binary_sensor', unit: ''},
    43: {name: 'tamper', type: 'binary_sensor', unit: ''},
    44: {name: 'vibration', type: 'binary_sensor', unit: ''},
    45: {name: 'window', type: 'binary_sensor', unit: ''},
    46: {name: 'humidity', type: 'sensor', unit: '%'},
    47: {name: 'moisture', type: 'sensor', unit: '%'},
    58: {name: 'button', type: 'button', unit: ''},
    60: {name: 'dimmer', type: 'dimmer', unit: ''},
    61: {name: 'count', type: 'sensor', unit: ''},
    62: {name: 'count', type: 'sensor', unit: ''},
    63: {name: 'rotation', type: 'sensor', unit: '°'},
    64: {name: 'distance_mm', type: 'sensor', unit: 'mm'},
    65: {name: 'distance_m', type: 'sensor', unit: 'm'},
    66: {name: 'duration', type: 'sensor', unit: 's'},
    67: {name: 'current', type: 'sensor', unit: 'A'},
    68: {name: 'speed', type: 'sensor', unit: 'm/s'},
    69: {name: 'temperature', type: 'sensor', unit: '° C'},
    70: {name: 'uv_index', type: 'sensor', unit: ''},
    71: {name: 'volume', type: 'sensor', unit: 'L'},
    72: {name: 'volume', type: 'sensor', unit: 'mL'},
    73: {name: 'volume_flow_rate', type: 'sensor', unit: 'm3/hr'},
    74: {name: 'voltage', type: 'sensor', unit: 'V'},
    75: {name: 'gas', type: 'sensor', unit: 'm3'},
    76: {name: 'gas', type: 'sensor', unit: 'm3'},
    77: {name: 'energy', type: 'sensor', unit: 'kWh'},
    78: {name: 'volume', type: 'sensor', unit: 'L'},
    79: {name: 'water', type: 'sensor', unit: 'L'},
    80: {name: 'timestamp', type: 'sensor', unit: ''},
    81: {name: 'acceleration', type: 'sensor', unit: 'm/s2'},
    82: {name: 'gyroscope', type: 'sensor', unit: '°/s'}
};
