--------------UP
CREATE TABLE ui.dashboard (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    name VARCHAR(300) NULL
);
CREATE UNIQUE INDEX ui_dashboard_id ON ui.dashboard (id);
--------------DOWN
DROP TABLE ui.dashboard;