--------------UP
CREATE TABLE ui.menu(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    name VARCHAR(300) NULL,
    url VARCHAR(500) NULL,
    icon_path VARCHAR(500) NULL
);
CREATE UNIQUE INDEX ui_menu_id ON ui.menu(id);
--------------DOWN
DROP TABLE ui.menu;
