{
 "title": "Energy Usage Variants",
 "description": "A dashboard that shows your home energy usage. Using Prometheus, Home Assistant and the Emporia Vue 2.",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "watt_price", "label": "Price per Watt", "query": "0.00015" },
   {
    "name": "devices",
    "label": "Devices",
    "query": "SELECT\n    id AS __value,\n    CASE WHEN\n        jdoc #>'{info, name}' != 'null'\n    THEN\n        jdoc #>> '{info, name}'\n    ELSE\n        jdoc #>> '{info, id}'\n    END AS __text\nfrom device.list;"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 5 Devices Currently Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(se.external_id) id,\n  MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) - MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (prev_val_min / 1000) * 60 ELSE prev_val_min END) watts\nFROM device.mv__em_total_act_5_min_history_20_days s\nLEFT JOIN device.list se ON s.id = se.id\nWHERE\n    1 = 1\n    AND s.id IN($devices)\n    AND s.field_group IN (\n        'emdata:*.total_act',\n        'em1data:*.total_act_energy',\n        'switch:*.aenergy.total'\n    )\n    AND s.bucket BETWEEN now() - '1 hour'::INTERVAL AND NOW()\nGROUP BY\n  s.id\nORDER BY watts DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Current Month Total Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    t1.bucket,\n    SUM(t1.diff) watts\nFROM (\n    SELECT\n      s.id,\n      s.bucket::date,\n      MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) - MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (prev_val_min / 1000) * 60 ELSE prev_val_min END) diff\n    FROM device.mv__em_total_act_5_min_history_20_days s\n    WHERE\n        1 = 1\n        AND s.id IN($devices)\n        AND s.field_group IN (\n            'emdata:*.total_act',\n            'em1data:*.total_act_energy',\n            'switch:*.aenergy.total'\n        )\n        AND s.bucket BETWEEN date_trunc('month', current_date) AND NOW()\n    GROUP BY\n      s.id,\n      s.bucket::date\n  ) t1\n  GROUP BY\n    t1.bucket"
    }
   ]
  },
  {
   "title": "Current Month Bill ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    SUM(t1.diff) * $watt_price AS price\nFROM (\n    SELECT\n      s.id,\n      s.bucket::date,\n      MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) - MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (prev_val_min / 1000) * 60 ELSE prev_val_min END) diff\n    FROM device.mv__em_total_act_5_min_history_20_days s\n    WHERE\n        1 = 1\n        AND s.id IN($devices)\n        AND s.field_group IN (\n            'emdata:*.total_act',\n            'em1data:*.total_act_energy',\n            'switch:*.aenergy.total'\n        )\n        AND s.bucket BETWEEN date_trunc('month', current_date) AND NOW()\n    GROUP BY\n      s.id,\n      s.bucket::date\n  ) t1\n"
    }
   ]
  },
  {
   "title": "Current Day Power Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    t1.b bucket,\n    sum(diff) watts\nFROM (\n    SELECT\n      s.id,\n      time_bucket('1 hours', s.bucket) b,\n      MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) - MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (prev_val_min / 1000) * 60 ELSE prev_val_min END) diff\n    FROM device.mv__em_total_act_5_min_history_20_days s\n    WHERE\n        1 = 1\n        AND s.id IN($devices)\n        AND s.field_group IN (\n            'emdata:*.total_act',\n            'em1data:*.total_act_energy',\n            'switch:*.aenergy.total'\n        )\n        AND s.bucket BETWEEN now() - '1 day'::INTERVAL AND NOW()\n    GROUP BY\n      s.id,\n      b\n) t1\ngroup by t1.b"
    }
   ]
  },
  {
   "title": "Current Day Power Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    SUM(t1.diff) * $watt_price AS price\nFROM (\n    SELECT\n      s.id,\n      s.bucket::date,\n      MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) - MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (prev_val_min / 1000) * 60 ELSE prev_val_min END) diff\n    FROM device.mv__em_total_act_5_min_history_20_days s\n    WHERE\n        1 = 1\n        AND s.id IN($devices)\n        AND s.field_group IN (\n            'emdata:*.total_act',\n            'em1data:*.total_act_energy',\n            'switch:*.aenergy.total'\n        )\n        AND s.bucket BETWEEN now()::date::timestamp AND NOW()\n    GROUP BY\n      s.id,\n      s.bucket::date\n  ) t1"
    }
   ]
  },
  {
   "title": "Month Power Total",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ss.external_id,\n  MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) -\n  MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (prev_val_min / 1000) * 60 ELSE prev_val_min END) watts\nFROM device.mv__em_total_act_5_min_history_20_days s\nLEFT JOIN device.list ss ON s.id = ss.id\nWHERE\n    1 = 1\n    AND s.id IN($devices)\n    AND s.field_group IN (\n        'emdata:*.total_act',\n        'em1data:*.total_act_energy',\n        'switch:*.aenergy.total'\n    )\n    AND s.bucket BETWEEN date_trunc('month', now()) AND NOW()\nGROUP BY\n  s.id,\n  ss.external_id"
    }
   ]
  },
  {
   "title": "Hourly Power by Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n    s.external_id,\n    $__timeGroupAlias(t1.bucket, '1h'),\n    pw watts\nFROM (\n    WITH main as (\n        SELECT\n            date_trunc('hour', s.bucket) bucket,\n            s.id,\n            MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) watts,\n            ROW_NUMBER () OVER (PARTITION BY s.id ORDER BY s.id, date_trunc('hour', s.bucket)) rn\n        FROM device.mv__em_total_act_5_min_history_20_days s\n        WHERE\n            s.id IN($devices)\n            AND s.field_group IN (\n                'emdata:*.total_act',\n                'em1data:*.total_act_energy',\n                'switch:*.aenergy.total'\n            )\n            AND s.bucket BETWEEN now()::date - interval '24h' AND NOW()\n        GROUP BY\n            s.id,\n            date_trunc('hour', s.bucket)\n        ORDER BY\n            s.id\n    )\n    select\n        t1.*,\n        (t1.watts - CASE WHEN t2.watts IS NULL THEN 0 ELSE t2.watts END) pw\n        FROM main t1\n        LEFT JOIN main t2 ON t2.id = t1.id AND t2.rn = t1.rn - 1\n) t1\nLEFT JOIN device.list s ON s.id = t1.id"
    }
   ]
  },
  {
   "title": "Top 5 Devices Last 7 Days",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(se.external_id) id,\n  MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) - MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (prev_val_min / 1000) * 60 ELSE prev_val_min END) watts\nFROM device.mv__em_total_act_5_min_history_20_days s\nLEFT JOIN device.list se ON s.id = se.id\nWHERE\n    1 = 1\n    AND s.id IN($devices)\n    AND s.field_group IN (\n        'emdata:*.total_act',\n        'em1data:*.total_act_energy',\n        'switch:*.aenergy.total'\n    )\n    AND s.bucket BETWEEN now() - '7 days'::INTERVAL AND NOW()\nGROUP BY\n  s.id\nORDER BY watts DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Daily Power Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n    b bucket,\n    SUM(diff) watts\nFROM (\n    SELECT\n        s.id,\n        date_trunc('day', s.bucket) b,\n        MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (s.value_max / 1000) * 60 ELSE s.value_max END) -\n        MIN(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (s.prev_val_min / 1000) * 60 ELSE s.prev_val_min END) diff\n    FROM device.mv__em_total_act_5_min_history_20_days s\n    WHERE\n        1 = 1\n        AND s.id IN($devices)\n        AND s.field_group IN (\n            'emdata:*.total_act',\n            'em1data:*.total_act_energy',\n            'switch:*.aenergy.total'\n        )\n        AND s.bucket BETWEEN date_trunc('day', now()) - INTERVAL '8 days' AND NOW()\n    GROUP BY\n        s.id,\n        b\n    ORDER BY b, s.id\n) x\nGROUP BY b"
    }
   ]
  },
  {
   "title": "Power Spikes This Week",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(s.bucket, '1h'),\n    MAX(CASE WHEN s.field_group = 'switch:*.aenergy.total' THEN (value_max / 1000) * 60 ELSE value_max END) watts\nFROM device.mv__em_total_act_5_min_history_20_days s\nWHERE\n    s.id IN($devices)\n    AND s.field_group IN (\n        'emdata:*.total_act',\n        'em1data:*.total_act_energy',\n        'switch:*.aenergy.total'\n    )\n    AND s.bucket BETWEEN now() - INTERVAL '7 days' AND NOW()\nGROUP BY\n    s.id,\n    \"time\"\nORDER BY \"time\", s.id"
    }
   ]
  },
  {
   "title": "Presence",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT b bucket, presence, se.external_id FROM (\n  SELECT\n      time_bucket_gapfill(INTERVAL '5 min', s.bucket, NOW() - interval '7 days', NOW()) as b,\n      s.id, CASE WHEN MIN(s.field) IS NULL THEN 0 ELSE 1 END presence\n  FROM\n      device.mv__status_presence s\n  WHERE\n      s.id IN($devices)\n      AND $__timeFilter(s.bucket)\n  GROUP BY b, s.id\n  ORDER BY b,s.id\n) s\nLEFT JOIN device.list se ON s.id = se.id;"
    }
   ]
  }
 ]
}